socialmedia/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(),name='signup'),
]

socialmedia/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<slug:username>/', views.UserPosts.as_view(), name='for_user'),
    path('by/<str:username>/<int:pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name='delete'),
]

socialmedia/socialmedia/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThnaksPage.as_view(), name='thanks'),
    path('posts/',include('posts.urls',namespace='posts')),
    path('groups/',include('groups.urls',namespace='groups')),
]

socialmedia/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Star Social</title>

    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    

    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Montserrat">

    <link rel="stylesheet" href="{% static '/socialmedia/css/master.css' %}">
</head>
<body>
    <nav class="navbar mynav" role="navigation" id="navbar">
        <div class="container">
            <a class="navbar-brand mynav" href="{% url 'home' %}">Star Social</a>

            <ul class="nav navbar navbar-right">
                {% if user.is_authenticated %}
                 <li class="nav-item"><a href="{% url 'posts:create' %}" class="nav-link active">Post</a></li>
                 <li class="nav-item"><a href="{% url 'groups:all' %}" class="nav-link active">Groups</a></li>
                 <li class="nav-item"><a href="{% url 'groups:create' %}" class="nav-link active">Create Groups</a></li>
                 <li class="nav-item"><a href="{% url 'accounts:logout' %}" class="nav-link active">Log Out</a></li>
                {% else %}
                 <li class="nav-item"><a href="{% url 'groups:all' %} " class="nav-link active">Groups</a></li>
                 <li class="nav-item"><a href="{% url 'accounts:login' %}" class="nav-link active">Log In</a></li>
                 <li class="nav-item"><a class="nav-link active" href="{% url 'accounts:signup' %}">Sign Up</a></li>
                {% endif %}

            </ul>
        </div>

    </nav>
    <div class="container mycontent">
        {% block content %}

        {% endblock %}
    </div>
    
    <canvas id="canvas"></canvas>

    <span id="note">Click to add fireflies</span>
</body>
<script src="{% static 'socialmedia/js/master.js'%}" type="text/javascript" ></script>
</html>

socialmedia/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1> Welcome to Star Social! </h1>
{% endblock %}

socialmedia/templates/test.html
{% extends 'base.html' %}

{% block content %}
<h1>Thanks for visiting, come back soon!</h1>

{% endblock %}

socialmedia/templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting! Come back soon!</h1>

{% endblock %}